config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  #root to: 'meals#index'

  root to: 'pages#home'
  get '/pages/results'
  resources :meals do
    resources :ingredients
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/food.rb
class Food < ApplicationRecord
  has_many :ingredients

  validates :name, uniqueness: true, presence: true
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  belongs_to :meal
  belongs_to :food

  validates :description, presence: true
  validates :meal_id, presence: true
  validates :food_id, presence: true
  validates :food_id, uniqueness: { scope: :meal_id }
end

app/models/meal.rb
class Meal < ApplicationRecord
  has_many :ingredients, dependent: :destroy
  has_many :foods, through: :ingredients

  validates :name, uniqueness: true, presence: true
end

app/models/transport.rb
class Transport < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/ingredients_controller.rb
class IngredientsController < ApplicationController
  def new
    @meal = Meal.find(params[:meal_id])
    @ingredient = Ingredient.new
  end

  def create
    @meal = Meal.find(params[:meal_id])
    @ingredient = Ingredient.new(ingredient_params)
    @ingredient.meal_id = @meal.id

    if @ingredient.save
      redirect_to @meal, notice: 'Ingredient was successfully created.'
    else
      render :new
    end
  end

  def destroy
    @ingredient = Ingredient.find(params[:id])
    @meal = @ingredient.meal
    @ingredient.destroy
    redirect_to meal_path(@meal)
  end

  private

  def ingredient_params
    params.require(:ingredient).permit(:description, :meal_id, :food_id)
  end

end

app/controllers/meals_controller.rb
class MealsController < ApplicationController
  def index
    @meals = Meal.all
  end

  def show
    @meal = Meal.find(params[:id])
    @meal.emission_total = 0

    @meal.ingredients.each do |ingredient|
      @meal.emission_total += Food.find(ingredient.food_id).emission_rate * Food.find(ingredient.food_id).average_portion_size
    end

    car = Transport.where(name: 'Car')[0]
    train = Transport.where(name: 'Train')[0]
    domestic_flight = Transport.where(name: 'Flight (Domestic)')[0]
    short_flight = Transport.where(name: 'Flight (Short Haul)')[0]
    long_flight = Transport.where(name: 'Flight (Long Haul)')[0]

    @car_km = @meal.emission_total / car.emissions
    @train_km = @meal.emission_total / train.emissions
    @domestic_flight_km = @meal.emission_total / domestic_flight.emissions
    @short_flight_km = @meal.emission_total / short_flight.emissions
    @long_flight_km = @meal.emission_total / long_flight.emissions
  end

  def new
    @meal = Meal.new
  end

  def create
    @meal = Meal.new(meal_params)
    if @meal.save
      redirect_to @meal, notice: 'Meal was successfully created.'
    else
      render :new
    end
  end

  private

  def meal_params
    params.require(:meal).permit(:name, :photo)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def results
    @food = Food.where(name: params[:diet]["food"])[0]
    emissions_per_kg = @food.emission_rate
    @one_year_emissions = params[:diet]["amount"].to_f * emissions_per_kg.to_f * @food.average_portion_size.to_f

    if params["diet"]["amount"] == "12"
      @amount = "once a month"
    elsif params["diet"]["amount"] == "52"
      @amount = "once a week"
    elsif params["diet"]["amount"] == "156"
      @amount = "3 times a week"
    elsif params["diet"]["amount"] == "365"
      @amount = "once a day"
    elsif params["diet"]["amount"] == "1095"
      @amount = "in every meal"
    end

    car = Transport.where(name: 'Car')[0]
    train = Transport.where(name: 'Train')[0]
    domestic_flight = Transport.where(name: 'Flight (Domestic)')[0]
    short_flight = Transport.where(name: 'Flight (Short Haul)')[0]
    long_flight = Transport.where(name: 'Flight (Long Haul)')[0]

    @car_km = @one_year_emissions / car.emissions
    @train_km = @one_year_emissions / train.emissions
    @domestic_flight_km = @one_year_emissions / domestic_flight.emissions
    @short_flight_km = @one_year_emissions / short_flight.emissions
    @long_flight_km = @one_year_emissions / long_flight.emissions
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ingredients_helper.rb
module IngredientsHelper
end

app/helpers/meals_helper.rb
module MealsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/ingredients/new.html.erb
<div>
  <h1>Add a new Ingredient</h1>


  <%= simple_form_for([@meal, @ingredient]) do |f| %>
    <%= f.association :food %>
    <%= f.input :description %>
    <%= f.button :submit %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>DietTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navbar' %>
    <%= yield %>
  </body>
</html>

app/views/meals/_form.html.erb
<%= simple_form_for(@meal) do |f| %>
  <%= f.input :name %>
  <%= f.button :submit %>
<% end %>

app/views/meals/index.html.erb
<div class="main-container">
  <div>
    <div class="header">
      <h1>Your Meals</h1>
    </div>
  </div>

  <% num = 0 %>

  <div>
    <div>
      <% num += 1 %>
      <div class="cards">
        <% @meals.each do |meal| %>
            <%= link_to meal do %>
              <div class="card-category" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.3)), url(https://raw.githubusercontent.com/lewagon/fullstack-images/master/uikit/breakfast.jpg)">
                <%=meal.name%>
              </div>
            <% end %>
          </ul>
        <% end %>
      </div>
    </div>
  </div>

  <div class="add-meal">
    <p><%= link_to "Add a new meal", new_meal_path %></p>
  </div>
</div>

app/views/meals/new.html.erb
<div>

<h1>New Meal</h1>

<%= render 'form', meal: @meal %>

</div>

app/views/meals/show.html.erb
<div class="main-container">
  <div class="header">
    <h1><%= @meal.name %></h1>
  </div>

  <div>
    <div class="meal-rating">
      <h4>1 serving of this meal results in the emission of</h4>
      <h2><%= @meal.emission_total %> kg</h2>
      <h4>of CO2 into the atmosphere approximately</h4>
    </div>

    <h2>annual equivalents...</h2>

    <table class="travel-equivalents">
      <tr>
        <th><p>Frequency</p></th>
        <th><p>Car</p></th>
        <th><p>Train</p></th>
        <th><p>Domestic Flight</p></th>
        <th><p>Sh. Haul Flight</p></th>
        <th><p>L. Haul Flight</p></th>
      </tr>
      <% i=0 %>
      <% frequencies = ["1/month", "1/week", "3/week", "1/day", "every meal"] %>
      <% [12, 52, 156, 365, 1095].each do |frequency| %>
        <tr>
          <td><p><%= frequencies[i] %></p></td>
          <td><p><%= (@car_km * frequency).to_i %></p></td>
          <td><p><%= (@train_km * frequency).to_i %></p></td>
          <td><p><%= (@domestic_flight_km * frequency).to_i %></p></td>
          <td><p><%= (@short_flight_km * frequency).to_i %></p></td>
          <td><p><%= (@long_flight_km * frequency).to_i %></p></td>
        </tr>
      <% i+=1 %>
      <% end %>
    </table>

    <h2>by ingredient...</h2>

    <table class="">
      <tr>
        <th><p>Ingredient</p></th>
        <th><p>Description</p></th>
        <th><p>Emissions*</p></th>
      </tr>
      <% @meal.ingredients.each do |ingredient| %>
        <tr>
          <td><p><%= Food.find(ingredient.food_id).name %></p></td>
          <td><p><%= ingredient.description %></p></td>
          <td><p><%= Food.find(ingredient.food_id).emission_rate %></p> </td>
        </tr>
      <% end %>
    </table>
    <p>* = kg of CO2 emitted per kg of ingredient produced</p>
  </div>

  <%= link_to "Add an ingredient", new_meal_ingredient_path(@meal) %>
</div>

app/views/pages/home.html.erb
<div class="main-container">
  <div>
    <div class="header">
      <h1>DietTracker</h1>
    </div>
  </div>


  <div class="intro-form">
    <div class="intro-description">
      <h1><b> Welcome to DietTracker.</b></h1>
      <br>
      <h3>Track how your diet affects your carbon footprint with DietTracker!</h3>
      <br>
      <h4>One of the largest contributors to peoples individual carbon footprints is their diet. DietTracker helps you understand your diet's affect on the planet through tailored emission statistics and meal ratings.</h4>
      <br>
      <h4><b>Choose an ingredient, how often you eat it and rate!</b></h4>
      <br>
      <h4>You can store the meals you eat by ingredient and then DietTracker will provide a rating on how environmentally friendly it is! Or you can get started with a Quick-rate to the right. Choose an ingredient, how often you eat it and rate!</h4>
    </div>

    <div class="button-form-container">
      <div class="quick-form">
        <h1>Quick-Rate</h1>
        <%= simple_form_for :diet, url: pages_results_path, method: "GET" do |f| %>
          <div class="p-3">
            <div class="home-form">
              <%= f.input :food, collection: ["Beef", "Lamb", "Cheese", "Farmed Salmon", "Turkey", "Chicken", "Canned Tuna", "Eggs", "Potatoes", "Rice", "Peanut Butter", "Nuts", "Yogurt", "Broccoli", "Tofu", "Dry Beans", "Milk (2%)", "Tomatoes", "Lentils"] %>
              <%= f.input :amount, collection: [["Once a month", 12], ["Once a week", 52], ["3 times a week", 156], ["Once a day", 365], ["Every meal", 1095]] %>
            <!-- :amount tracks the amount of times the specific food is eaten in a year -->
            </div>
          <%= f.button :submit, "Search", class: "btn btn-dark btn-search" %>
          </div>
        <% end %>
      </div>
      <div class="front-buttons">
        <%= link_to "Your meals", "#", class: "btn btn-flat" %>
        <%= link_to "Info", "#", class: "btn btn-flat" %>
      </div>
    </div>
  </div>
</div>

app/views/pages/results.html.erb
<div class="main-container">
  <div>
    <div class="header">
      <h1>DietTracker</h1>
    </div>
  </div>


  <div class="intro-form">

    <div class="intro-description">
      <h1><b> Welcome to DietTracker.</b></h1>
      <br>
      <h3>Track how your diet affects your carbon footprint with DietTracker!</h3>
      <br>
      <h4>One of the largest contributors to peoples individual carbon footprints is their diet. DietTracker helps you understand your diet's affect on the planet through tailored emission statistics and meal ratings.</h4>
      <br>
      <h4><b>Get started by choosing a food and how much you eat it!</b></h4>
    </div>
    <div class="quick-form">
      <div class="results-container">
        <div class="front-form-header">
          <h1>Quick-Rate</h1>
          <%= simple_form_for :diet, url: root_path, method: "GET" do |f| %>
            <%= f.button :submit, "Reset", class: "btn btn-dark btn-reset" %>
          <% end %>
        </div>
        <br>
        <h3>Eating <%= @food.name.downcase %> <%= @amount %> leads to</h3>
        <h1 class="m-3"><b><%= @one_year_emissions.floor %>kg</b></h1>
        <h4>of CO2 per year. This is similar to travelling ... </h4>
        <div class="travel-figures mt-4">
          <div class="m-4">
            <h4><b><%= @car_km.floor %>km</b> by car</h4>
            <h4><b><%= @train_km.floor %>km</b> by train</h4>
            <h4><b><%= @domestic_flight_km.floor %>km</b> on a domestic flight</h4>
            <h4><b><%= @short_flight_km.floor %>km</b> by short haul flight</h4>
            <h4><b><%= @long_flight_km.floor %>km</b> by long haul flight</h4>
          </div>
        </div>
      </div>
    </div>

  </div>
</div>

app/views/shared/_navbar.html.erb
<div class="navbar navbar-expand-sm navbar-light navbar-lewagon">
  <a class="navbar-brand" href="/">DT</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>


  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <a class="nav-link" href="#">Quick Rate</a>
      </li>
      <li class="nav-item">
        <a class="nav-link" href="/meals">Your Meals</a>
      </li>
      <li class="nav-item dropdown">
        <img class="avatar dropdown-toggle" id="navbarDropdown" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false" src="https://kitt.lewagon.com/placeholder/users/ssaunier" />
        <div class="dropdown-menu dropdown-menu-right" aria-labelledby="navbarDropdown">
          <a class="dropdown-item" href="#">Action</a>
          <a class="dropdown-item" href="#">Another action</a>
        </div>
      </li>
    </ul>
  </div>
</div>